spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  hikari:
    driver-class-name: org.postgresql.Driver
